apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: logs-count-scrape-config
  namespace: o11y
#  namespace: monitoring
  labels:
    ## <1>
    prometheus: o11y-prometheus

spec:
  staticConfigs:
    - labels:
        job: kubelet-metrics-scrape-job
      targets:
        ## <2>
        - logs-count-collector:8889

