#theme: jekyll-theme-minimal
title: Service Foundry
description: Bookmark this to keep an eye on my project updates!
markdown: kramdown
destination: ./site
asciidoc:
  attributes:
    source-highlighter: rouge
    icons: font
    toc: left
    toc-title: Table of Contents (Nav)
    #number-sections: true

plugins:
  - jekyll-asciidoc