#theme: jekyll-theme-minimal
title: Service Foundry
description: Bookmark this to keep an eye on my project updates!
markdown: kramdown
destination: ./docs
asciidoc:
  attributes:
    source-highlighter: rouge
    icons: font
    toc: right
    toc-title: On this page
#    number-sections: true

plugins:
  - jekyll-asciidoc