= Service Foundry

:toc: macro
:toclevels: 3

:toc-title: Table of Contents

== Introduction

Service Foundry is a platform for deploying and managing applications in a Kubernetes environment. It provides a set of tools and best practices for building, deploying, and scaling applications in a cloud-native way.

== Submodules

* infra-foundry
* sso-foundry
* o11y-foundry
* backend-foundry (Framework for building backend applications)
* bigdata-foundry


== Jekyll Configuration

Github Pages does not support all Jekyll plugins. To use the `jekyll-asciidoc` plugin, you need to run Jekyll locally. You can do this by using the `--baseurl` option to specify the base URL for your site.

=== Local Build

On local, the destination directory is 'pages' and the base URL is `/service-foundry/pages`. You can run the following command to build the site locally:

_config.yml on local
[.yaml]
----
#theme: jekyll-theme-minimal
title: Service Foundry
description: Bookmark this to keep an eye on my project updates!
markdown: kramdown
destination: ./pages
asciidoc:
  attributes:
    source-highlighter: rouge
    icons: font
    toc: right
    toc-title: On this page
#    number-sections: true

# these 2 lines are needed to make the site work with GitHub Pages
# use {{ site.baseurl }} in your links
# for local development run the command below
# bundle exec jekyll serve --baseurl "/service-foundry"
baseurl: "/service-foundry"
url: "https://nsalexamy.github.io"

plugins:
  - jekyll-asciidoc
----

=== Github Pages

On Github, Jekyll just includes index.html and processed Asciidoc files in the pages directory. The `_config.yml` file is used to configure the Jekyll site. You can use the following configuration for your `_config.yml` file:

._config.yml on github
[.yaml]
----
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
include: ["index.html", "pages/", "assets/"]
----


== Local Development

To run the Jekyll site locally, you need to install the required gems and run the Jekyll server. You can do this by running the following commands:

[.terminal]
----
$ bundle exec jekyll serve --baseurl "/service-foundry/pages"
----
