- name: observability-foundry
  label: Observability Foundry
  icon: chart-no-axes-combined
  icon-color: text-indigo-500

  short-description: Pre-configured Observability Platform for Kubernetes Workloads
  description: >
    The <strong>Observability Foundry</strong> provides a comprehensive suite of tools for <strong>observability</strong> in under <strong>5 minutes </strong>. 
    It includes <b>Mimir</b> and <b>Prometheus</b> for metrics collection, <b>Tempo</b> and <b>Jaeger</b> for traces collection, <b>Loki</b> and <b>OpenSearch</b> for log management, and <b>Grafana</b> for visualization, all integrated with <b>SSO</b> capabilities.

  url: observability-foundry/
  intro-image: observability-foundry/images/observability-foundry-intro.png
  key-features:
    - title: Rapid Development
      icon: rocket
      description: Accelerate development with pre-configured observability tools. Spin up a production-grade observability platform on your Kubernetes cluster in under <strong>5 minutes</strong> using a Helm-based installation.
    - title: Unified Telemetry Pipeline
      icon: workflow
      description: Collect and correlate <strong>logs, traces, and metrics</strong> from all components of your system, including frontend, backend, and containerized workloads.
    - title: OpenTelemetry Native
      icon: activity
      description: Built on the <strong>OpenTelemetry standard</strong>, all telemetry data is collected using a vendor-neutral, industry-standard protocol for maximum compatibility and future-proofing.
    - title: Dual OpenTelemetry Collector Architecture for Applications and Infrastructure
      icon: network
      description: The observability stack is designed with a dual OpenTelemetry Collector architecture, enabling efficient data collection from both <strong>applications</strong> and <strong>infrastructure</strong>. This ensures comprehensive observability across your entire system.
    - title: Zero Code Changes Required
      icon: zap-off
      description: Application instrumentation is performed using <strong>OpenTelemetry auto-instrumentation agents</strong>, meaning no source code modifications are needed to begin capturing observability data.
    - title: Grafana Integration
      icon: layout-dashboard
      description: Pre-configured <strong>Grafana dashboards</strong> for logs, traces, and metrics. Easily visualize your system, set up <strong>alerting rules</strong>, and perform <strong>real-time log analysis</strong> with intuitive queries.
    - title: OAuth2-Based Access Control
      icon: lock
      description: Integrate with your existing identity provider using <strong>OAuth2</strong>, and manage <strong>user authentication and access control</strong> with ease.
    - title: No External Dependencies
      icon: server-off
      description: Keep sensitive telemetry data inside your Kubernetes environment. No subscriptions or external storage are required — <strong>you retain full control</strong> over your data.
    - title: Flexible Resource Usage
      icon: repeat
      description: Deploy or tear down the observability stack <strong>on demand</strong>, making it ideal for testing, staging, and production environments with varying workloads.
    - title: Open Source Foundation
      icon: github
      description: Observability Foundry is built entirely on trusted and widely adopted <strong>open source technologies</strong> such as OpenTelemetry, Grafana, Loki, Jaeger, and Prometheus. This ensures transparency, community support, and long-term sustainability without vendor lock-in. You can audit the source code, contribute enhancements, or tailor the platform to meet specific security or compliance requirements.
- name: sso-foundry
  label: SSO Foundry
  icon: user-lock
  icon-color: text-indigo-500

  url: sso-foundry/
  short-description: Single Sign-on for Service Foundry
  description: SSO Foundry is a comprehensive solution for implementing Single Sign-On (SSO) in your Service Foundry environment. It provides a seamless authentication experience across all Service Foundry modules, ensuring secure and efficient user access management.
  key-features:
    - title: Seamless Integration
      description: Integrates with existing Service Foundry modules to provide a unified authentication experience.
    - title: OpenID Connect Support
      description: Supports OpenID Connect for secure and standardized authentication.
    - title: User Management
      description: >
        Provides tools for managing users, roles, and permissions across the Service Foundry ecosystem.  url: sso-foundry/
- name: backend-foundry
  label: Spring Backend Foundry
  icon: cloud-cog
  icon-color: text-indigo-500
  url: backend-foundry/
  short-description: Pre-configured Backend Platform for Spring Applications
  description: >
    The <strong>Backend Foundry</strong> provides a ready-to-use platform for deploying and managing Spring-based applications. It includes essential components like databases, message brokers, and service discovery, streamlining the development and deployment process.
  key-features:
    - title: Observability Enabled
      description: All backend applications built with Spring Backend Foundry come with built-in observability features, including logging, tracing, and metrics collection. This ensures that you can monitor and troubleshoot your applications effectively.
    - title: Config Management with Spring Cloud Config Watch
      description: Provides a centralized configuration management system that allows you to manage application configurations across different environments. It supports dynamic configuration updates, ensuring that your applications always run with the latest configurations.

- name: bigdata-foundry
  label: BigData Platform Foundry
  icon: package-search
  icon-color: text-indigo-500
  url: bigdata-foundry/
  short-description: Pre-configured Big Data Platform for Kubernetes
  description: >
    The <strong>BigData Foundry</strong> delivers a comprehensive big data platform tailored for Kubernetes environments. It includes tools for data processing, storage, and analytics, enabling efficient handling of large datasets.
  key-features:
    - title: Open Source Big Data Tools
      description: Leverages popular open source big data tools such as Apache Spark, Apache Kafka, and Apache Hadoop to provide a robust data processing and analytics platform.
    - title: Batch Scheduling with Apache Airflow
      description: Provides a powerful batch scheduling system using Apache Airflow, allowing you to define, schedule, and monitor complex data workflows with ease.
