apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-java-agent-config
data:
  agent.properties: |
    otel.instrumentation.jdbc.enabled=true
    otel.instrumentation.spring-webmvc.enabled=true
  logback.xml: |
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
        
        <root level="INFO">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>
