namespace: qc

resources:
  - postgresql-example-obi-deployment.yaml
  - postgresql-example-obi-service.yaml
  - postgresql-example-obi-configmap.yaml
  - postgresql-example-obi-secret.yaml
  - postgresql-example-obi-ingress.yaml