{
 "title": "JVM Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Used Memory(MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{jvm_memory_type=\"heap\"} / (1024 * 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Java Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "(\n                                      sum by(pod) (jvm_memory_used_bytes{jvm_memory_type=\"heap\"})\n                                      /\n                                      sum by(pod) (jvm_memory_limit_bytes{jvm_memory_type=\"heap\"})\n                                    ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Utilization Ratio(2m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod)(avg_over_time(jvm_cpu_recent_utilization_ratio[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Count per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "targets": [
    { "expr": "sum by (pod)(jvm_thread_count)", "legendFormat": "__auto" }
   ]
  }
 ]
}