image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0-debian-12-r4 #16.2.0-debian-12-r20

auth:
  username: "pguser"
  database: "mydatabase"
  existingSecret: postgresql-credentials

primary:

  ## pgHbaConfiguration: |-
  ##   local all all trust
  ##   host all all localhost trust
  ##   host mydatabase mysuser 192.168.0.0/24 md5
  ##
  pgHbaConfiguration: |-
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust



    host    all             all             10.0.0.0/8              trust
  
  
  

  extendedConfiguration: |-
    wal_level = logical
    max_replication_slots = 10
    max_wal_senders = 10
    max_connections = 200


  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  #  nodeSelector:
  #    agentpool: depnodes




  persistence:
    existingClaim: "pvc-manual-postgresql"
