apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual-postgresql
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0727f295bf73bfb34::fsap-0bf7bce9b69d2fd02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manual-postgresql
  namespace: manual
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: pv-manual-postgresql
  resources:
    requests:
      storage: 8Gi
