apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
  namespace: cert-manager
spec:
  acme:
    # Your contact email (used for renewal notices)
    email: credemol@gmail.com

    # Let’s Encrypt production server
    # For testing, use: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory

    # Secret where the ACME account private key is stored
    privateKeySecretRef:
      name: letsencrypt-http-key

    # Use HTTP-01 challenge via Traefik ingress
    solvers:
      - http01:
          ingress:
            class: traefik