= SSL with Let's Encrypt

== Introduction

This guide provides step-by-step instructions on how to secure your applications with SSL certificates from Let's Encrypt using the Service Foundry Console. By following this guide, you will be able to set up automated SSL certificate management for your services, ensuring secure communication over HTTPS.

== Prerequisites

Before you begin, ensure you have the following prerequisites in place:

* Domain Name: You need a registered domain name that you own or control.
* DNS Configuration: Ensure that your domain's DNS records are correctly configured to point to your Kubernetes cluster's ingress controller.
* Kubernetes Cluster: A running Kubernetes cluster with access to deploy resources.


== Install cert-manager

== Install certbot

To obtain SSL certificates from Let's Encrypt, we will use certbot. Follow the instructions below to install certbot on your local machine or server.

=== Install certbot on MacOS

You can install certbot using Homebrew. Run the following command in your terminal:
[source,shell]
----
$ brew install certbot
----

== Obtain Challenge Tokens
To obtain SSL certificates from Let's Encrypt, you need to complete a domain validation process. This typically involves creating DNS TXT records or serving HTTP challenge files.

Follow the instructions provided by certbot to obtain the necessary challenge tokens for your domain.

[source,shell]
----
$ certbot certonly --manual --preferred-challenges dns -d yourdomain.com -d *.yourdomain.com --config-dir ./certbot --work-dir ./certbot --logs-dir ./certbot

Enter email address or hit Enter to skip.: your-email

#$ certbot certonly --manual --preferred-challenges dns -d servicefoundry.ca -d *.servicefoundry.ca
----

Output:
----
Saving debug log to /Users/young/Dev/alexamy/service-foundry/documents/sso-foundry/self-signed-certificate/letsencrypt.log
Requesting a certificate for servicefoundry.ca and *.servicefoundry.ca

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name:

_acme-challenge.servicefoundry.ca.

with the following value:

6tkFowyqJ78MQBvjbLUJ2JdfhVDrCh1CpPaBsDkmIOI

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Continue

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please deploy a DNS TXT record under the name:

_acme-challenge.servicefoundry.ca.

with the following value:

LXi9Tz8blGxN5v_wfdw000CeWl6SLs3gKyEx35PxEjY

(This must be set up in addition to the previous challenges; do not remove,
replace, or undo the previous challenge tasks yet. Note that you might be
asked to create multiple distinct TXT records with the same name. This is
permitted by DNS standards.)

Before continuing, verify the TXT record has been deployed. Depending on the DNS
provider, this may take some time, from a few seconds to multiple minutes. You can
check if it has finished deploying with aid of online tools, such as the Google
Admin Toolbox: https://toolbox.googleapps.com/apps/dig/#TXT/_acme-challenge.servicefoundry.ca.
Look for one or more bolded line(s) below the line ';ANSWER'. It should show the
value(s) you've just added.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Press Enter to Continue

Successfully received certificate.
Certificate is saved at: /Users/young/Dev/alexamy/service-foundry/documents/sso-foundry/self-signed-certificate/live/servicefoundry.ca/fullchain.pem
Key is saved at:         /Users/young/Dev/alexamy/service-foundry/documents/sso-foundry/self-signed-certificate/live/servicefoundry.ca/privkey.pem
This certificate expires on 2026-01-29.
These files will be updated when the certificate renews.

NEXT STEPS:
- This certificate will not be renewed automatically. Autorenewal of --manual certificates requires the use of an authentication hook script (--manual-auth-hook) but one was not provided. To renew this certificate, repeat this same certbot command before the certificate's expiry date.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

----

Move to Go Daddy, Domain > DNS, Click Add New Record,
Type: TXT
Name: _acme-challenge
Value: 201CZ97t__Ey652QQLuXoKtdpnMSSfgh-Re9-GjF55M
TTL: 1/2 Hour

And click Save.

The same for the second token.



== Resources

* https://letsencrypt.org/getting-started/
* https://certbot.eff.org/hosting_providers
* https://certbot.eff.org/