apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: oss-fluent-operator-3.4.2-helm-app:fluentbit.fluent.io/ClusterInput:fluent/tail
  creationTimestamp: "2025-10-07T22:58:54Z"
  generation: 1
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: tail
  resourceVersion: "86872"
  uid: d6e84fe8-0209-424a-b93f-babeaeb349e1
spec:
  tail:
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    memBufLimit: 100MB
    parser: docker
    path: /var/log/containers/*.log
    readFromHead: false
    refreshIntervalSeconds: 10
    skipEmptyLines: true
    skipLongLines: true
    storageType: memory
    tag: kube.*