apiVersion: fluentbit.fluent.io/v1alpha2
kind: FluentBit
metadata:
  name: fluentbit
  namespace: fluent
spec:
#  https://github.com/fluent/fluent-operator?tab=readme-ov-file#fluent-bit
#  image: fluent/fluent-bit:3.0.4
  image: ghcr.io/fluent/fluent-operator/fluent-bit
  fluentBitConfigName: fluentbit-config
  positionDB:
    storage: filesystem
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi