apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kubelet-metrics-scrape-config
  namespace: o11y
#  namespace: monitoring
  labels:
    ## <1>
    prometheus: o11y-prometheus

spec:
  staticConfigs:
    - labels:
        job: kubelet-metrics-scrape-job
      targets:
#        - kubelet-metrics-collector:8889
        ## <2>
        - kubelet-metrics-collector.monitoring.svc:8889