apiVersion: v1
kind: Endpoints
metadata:
  name: kubelet
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.2.90
      - ip: 192.168.33.203
    ports:
      - name: https-metrics
        port: 10250