apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-scraper
  namespace: monitoring
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: kubelet-metrics-reader
#rules:
#  - nonResourceURLs:
#      - /metrics
#      - /metrics/cadvisor
#      - /metrics/probes
#      - /metrics/resource
#    verbs: ["get"]
#  - apiGroups: [""]
#    resources: ["nodes", "nodes/metrics", "nodes/proxy"]
#    verbs: ["get", "list", "watch"]
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: kubelet-metrics-reader-binding
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: kubelet-metrics-reader
#subjects:
#  - kind: ServiceAccount
#    name: kubelet-scraper
#    namespace: monitoring
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-targetallocator-rb-monitoring
subjects:
  - kind: ServiceAccount
    name:  kubelet-scraper
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otel-targetallocator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-targetallocator-cr-rb-monitoring
subjects:
  - kind: ServiceAccount
    name:  kubelet-scraper
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otel-targetallocator-cr-role
  apiGroup: rbac.authorization.k8s.io