# Kubernetes Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyc-open-data-loader
  namespace: qc
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::445567090745:role/nsa2-sf_S3_CSI_Role"



