apiVersion: v1
kind: Secret
metadata:
  name: nyc-open-data-secret
  namespace: qc
  labels:
    provider: service-foundry
data:
  POSTGRES_URL: cG9zdGdyZXNxbDovL25zYTI6Y2hhbmdlaXRAcG9zdGdyZXNxbC5zZXJ2aWNlLWZvdW5kcnk6NTQzMi9ueWNfb3Blbl9kYXRh