apiVersion: v1
kind: ConfigMap
metadata:
  name: sf-obi-config
  namespace: service-foundry
data:
  obi-config.yml: |-
    discovery:
      instrument:
        - k8s_namespace: service-foundry
          k8s_pod_label:
            instrument: obi
            
    # https://opentelemetry.io/docs/zero-code/obi/configure/service-discovery/
    kubernetes:
      resource_labels:
        service.name:
          - override-svc-name
          - app.kubernetes.io/name
        service.namespace:
          - override-svc-namespace
          - app.kubernetes.io/part-of