= Setting up your own GitHub Helm Chart Repository

== Introduction

=== Step 1: Create a GitHub Repository (helm-charts)

Create a new GitHub repository to host your Helm charts. You can name it something like `helm-charts`. Make sure to initialize the repository with a README file.

=== Step 2: Create Helm Charts

Create your Helm charts using the `helm create` command. For example, to create a chart named `my-chart`, run the following command:

[source,shell]
----
$ helm create service-foundry-builder
----

Add or remove Helm template files as needed. You can also update a `values.yaml` file to customize the chart's configuration.

=== Step 3: Package Helm Charts
Package your Helm charts using the `helm package` command. This will create a `.tgz` file for each chart in the current directory.

[source,shell]
----
$ helm package service-foundry-builder
----

=== Step 4: Create an Index File

The index.yaml file is a metadata file that contains information about the charts in your repository. It is used by Helm to find and install charts from your repository.

Create an index file for your Helm charts using the `helm repo index` command. This will generate an `index.yaml` file that contains metadata about your charts.



[source,shell]
----
$ helm repo index . --url https://nsalexamy.github.io/helm-charts
----

=== Step 5: Commit and Push to GitHub

Add the generated `.tgz` files and `index.yaml` file to your GitHub repository. You can do this using the following commands:
[source,shell]
----
$ git add .
$ git commit -m "Add Helm charts"
$ git push origin main
----

=== Step 6: Host on GitHub Pages

Enable GitHub Pages for your repository. Go to the repository settings, scroll down to the "GitHub Pages" section, and select the `gh-pages` branch as the source. This will host your Helm charts on GitHub Pages.


. Create a new branch named `gh-pages` in your repository. You can do this on GitHub by clicking on the "New Branch" button and typing `gh-pages`. This will create a new branch for hosting your Helm charts.
. Enable GitHub Pages for your repository. Go to the repository settings, scroll down to the "GitHub Pages" section, and select the `gh-pages` branch as the source. This will host your Helm charts on GitHub Pages.
. Make sure to set the source to the `gh-pages` branch in the GitHub Pages settings. This will allow GitHub to serve the files from that branch as a website.
. Merge the main branch into the `gh-pages` branch. You can do this using the Pull Request feature on GitHub. Create a new pull request from the `main` branch to the `gh-pages` branch and merge it. This will copy the files from the main branch to the `gh-pages` branch.
. After merging, your Helm charts will be available at `https://<username>.github.io/<repository>/index.yaml`. You can access the index file by navigating to this URL in your web browser.

=== Step 7: Add the Repository to Helm

Add your GitHub repository as a Helm repository using the `helm repo add` command. Replace `<username>` with your GitHub username and `<repository>` with the name of your repository.

[source,shell]
----
$ helm repo add service-foundry https://nsalexamy.github.io/helm-charts

# Verify the repository is added
$ helm repo list
----

=== Step 8: Install Charts from Your Repository

You can now install charts from your GitHub Helm chart repository using the `helm install` command. For example, to install the `service-foundry-builder` chart, run the following command:

[source,shell]
----
$ helm install service-foundry-builder service-foundry/service-foundry-builder -n service-foundry --create-namespace
----

