apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: kubernetes-json-log
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  regex:
    # Capture the timestamp, stream, flags, and inner log message
    regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) F (?<log>.*)$'
    timeKey: time
    timeFormat: "%Y-%m-%dT%H:%M:%S.%LZ"