apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: otel-field-mapper
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/filter-order: "110"
spec:
  match: sf-backend.*
  filters:
    - modify:
        rules:
        - rename:
            trace_id: TraceId
        - rename:
            span_id: SpanId
        - rename:
            level: SeverityText
        - add:
            'resource.service.name': service-foundry-app-backend
        - add:
            'job.name': ${job.name}
