apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: otel-collector
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
#    component: "output"
spec:
#  https://docs.fluentbit.io/manual/data-pipeline/outputs/opentelemetry
  match: sf-backend.*
  opentelemetry:
    host: otel-collector.o11y
    port: 4318
#    grpc: on
#    http2: on # default is on

    logsUri: /v1/logs
#    tls: off
#    tls:
#      verify: false
    # Optional:
    # tls: off
    # logResponsePayload: true

    logsBodyKey: msg
    logsBodyKeyAttributes: true

#    logsTraceIdMessageKey: trace_id
#    logsSpanIdMessageKey: span_id
    # Map the log level text field from your log record:
#    logsSeverityTextMessageKey: level