# 32
#mode: standalone

rootUser: minioroot
rootPassword: minioroot

# 123
replicas: 2

# 144
persistence:
  size: 10Gi

# 365
users:
  - accessKey: accessKey
    secretKey: secretKey
    policy: none