apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage-loki-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a42550c7fe28aeda::fsap-0238e203fbce5d855
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
  namespace: o11y
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: pv-storage-loki-0  # Manually bind to PV
  resources:
    requests:
      storage: 10Gi