= Running a Local Kubernetes Cluster with Kind

:imagesdir: images
:images:

== Introduction

Kind, short for Kubernetes IN Docker, is a tool for running local Kubernetes clusters in Docker containers. It is a lightweight, easy-to-use tool for testing and developing Kubernetes applications locally. In this blog post, we will walk through the process of installing and using Kind to create and manage a local Kubernetes cluster.

== Prerequisites

Before we begin, make sure you have the following installed:

* Docker
* Kubectl
* Kind

== Installing Kind

To install Kind, you can use the following command:

```bash
brew install kind
```

== Creating a Kind Cluster

To create a Kind cluster, you can use the following command:

```bash
kind create cluster
```

=== Create a Kind Cluster with Worker Nodes

.k8s/kind-config.yaml
[source,yaml]
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
---

[source,bash]
-----
kind create cluster --config k8s/kind-config.yaml
-----

== Using Kind

To use Kind, you can use the following command:

```bash
kind get clusters
```

== Deleting a Kind Cluster

To delete a Kind cluster, you can use the following command:

```bash
kind delete cluster
```

== Conclusion

Kind is a lightweight, easy-to-use tool for running local Kubernetes clusters in Docker containers. It is a great tool for testing and developing Kubernetes applications locally.